- name: install kubernetes master on the node
  hosts: k8s_master
  tags: k8s-master
  roles:  
    - k8s-master
    - nginx-ingress

- name: install kubernetes node
  hosts: k8s_node
  tags: k8s-node
  roles:  
    - k8s-node